name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - main  # Deploy when changes are pushed to "main"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Authenticate with Google Cloud
        run: |
          echo "${{ secrets.GCP_SA_KEY }}" | base64 --decode > key.json
          gcloud auth activate-service-account --key-file=key.json
          gcloud config set project YOUR_PROJECT_ID

      - name: Build and push Docker image
        run: |
          docker build -t gcr.io/Ai-Auditor/ai-auditor .
          docker push gcr.io/Ai-Auditor/ai-auditor

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ai-auditor --image gcr.io/Ai-Auditor/ai-auditor --region us-central1 --platform managed --allow-unauthenticated
