name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - main  # Deploy when changes are pushed to "main"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Authenticate with Google Cloud
        run: |
          # Decode the base64 encoded key and write to key.json
          echo "${{ secrets.GCP_SA_KEY }}" | base64 --decode > key.json
          # Debug: Print the first few lines of key.json to ensure it looks like valid JSON.
          head -n 10 key.json
          # Authenticate with Google Cloud using the key
          gcloud auth activate-service-account --key-file=key.json
          gcloud config set project ai-auditor-450522
      
      
      
      

      - name: Build and push Docker image
        run: |
          docker build -t gcr.io/ai-auditor-450522/ai-auditor .
          docker push gcr.io/ai-auditor-450522/ai-auditor

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ai-auditor --image gcr.io/ai-auditor-450522/ai-auditor --region us-central1 --platform managed --allow-unauthenticated
